### ISSUE TITLE
RPI Image does not work

### ISSUE THREAD

**Issue by andybroger** [alexhaydock/pinewall#1]
Hi

Thanks for sharing this wonderful project. 

if i create the image for my rpi, the overlay don't get loaded from usb stick.
The x86 buildscripts work fine.

Any ideas?

KR Andy

**Comment by alexhaydock** [comment]
Hi!

Thanks for the comment. It's good to know that people are actually interested in this, and I'm glad you're finding the project useful!

I do think the RPi image needs some more testing before it works the same way as I've been using the x86 one in production. The Pi one seems to use mostly the same setup as x86 (i.e. the `mkimage.sh` script just amends the standard Alpine image by adding our additional packages). But I'm not sure in what ways exactly the Pi boot of Alpine is different to x86. Like you, I've not had much luck getting it to boot and load an APKOVERLAY from a separate USB drive, though I haven't done much testing of this and why it might be the case. I have had luck with putting the APKOVERLAY in the root of the disk that the Pi image gets written to though. But I accept that isn't ideal since it makes the whole system a bit less flexible, as you lose one of the main benefits of the x86 version, which is that the OS and config can be upgraded (or rolled back) independently of each other.

I don't actually have a Pi in production running this currently, unlike with the x86 version, so it might take me a little while to test things out but I'll try some experimentation and see what I can come up with. Let me know if you run into any solutions too!

**Comment by andybroger** [comment]
I tested the hole day, i didn't get it to work, my current solution is to put the overlay file on the sdcard. For the RPI this is totally fine. No need for additional sticks or something. and you can copy and clone the sd card pretty easy.

One thing that im struggling with,  is that i just have around 200mbit/s down & 300mbit/s up (RPI4b) and i have a 1gbit/s connection. Maybe its just a crappy USB NIC or I need to tune some NIC parameters.

**Comment by andybroger** [comment]
hi @alexhaydock I refactored a lot of your code into to fit my usecase.

Mainly I dropped the x86 support, maybe this could be added back again in the future. But for now im Focusing on the RPI Builds. I fine tuned a lot for the RPI, and there are now a lot of customisations in the config. So for me it does not make any sense to maintain two versions with the same build scripts.

I did a lot of performance tuning, so that I'm able to firewall/route arround 900mbit/s with a RPI4 ! Thats amazing! My test equipment is a rpi4b and a cm4 with dfrobots iot router pcb. I have also a rpi3b, which i want to test also in the future. Currently i don't believe that there is consumer router for ~150$ is capable of this linespeed. 

Next steps will be to get more information out of the box / maybe with netflow, or directly with suricata on the rpi 😈. To Log/Monitor i use a Grafana/Loki/Prometheus Stack.

If its okey for you, i maintain the fork under my profile as a public repo. Of course i would mention you in the Readme.
Also I wanted to ask if its okey, that I could borrow your Logo & Name as it looks really great.

But i could totally understand that you dont want me to do that.

**Comment by alexhaydock** [comment]
> hi @alexhaydock I refactored a lot of your code into to fit my usecase.
> 
> Mainly I dropped the x86 support, maybe this could be added back again in the future. But for now im Focusing on the RPI Builds. I fine tuned a lot for the RPI, and there are now a lot of customisations in the config. So for me it does not make any sense to maintain two versions with the same build scripts.

This is great to hear! Glad to hear it's useful to you. As you can tell, I haven't paid as much attention to the Pi build as I have to the x86 one yet, but if there are specific tweaks and bits of tuning you added to improve the Pi support that you'd like to highlight, then I'd definitely be interested, since it probably makes sense for me to bring at least some of them into the main branch here.

> I did a lot of performance tuning, so that I'm able to firewall/route arround 900mbit/s with a RPI4 ! Thats amazing! My test equipment is a rpi4b and a cm4 with dfrobots iot router pcb. I have also a rpi3b, which i want to test also in the future. Currently i don't believe that there is consumer router for ~150$ is capable of this linespeed.

Those performance stats are genuinely impressive! :open_mouth: I didn't expect such high performance honestly. Are you using the default R8169 module to provide the drivers for the DFRobot NIC?

I don't actually have one of the DFRobot boards yet, but I was interested in getting one (and a CM4) for this specific project, but at the time I looked they were only offering DKMS drivers so there was no Alpine support. I did [file a bug about that](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12662) upstream with Alpine, but it turns out the RPi kernel build configs come straight from upstream so it seems it eventually got added [by this commit](https://github.com/raspberrypi/linux/commit/95c9767aac139dda4f43bdf4355fb9317865fbfb). If I can use the board without needing to compile my own kernel modules that'd be ideal.

> Next steps will be to get more information out of the box / maybe with netflow, or directly with suricata on the rpi smiling_imp. To Log/Monitor i use a Grafana/Loki/Prometheus Stack.

Also good to hear! I'd be particularly interested to see a decent netflow config using this setup! That's one that is definitely on my wishlist for the project in the future.

> If its okey for you, i maintain the fork under my profile as a public repo. Of course i would mention you in the Readme. Also I wanted to ask if its okey, that I could borrow your Logo & Name as it looks really great.

Feel free, I definitely encourage it - especially if you are making improvements to what I've got here! I [added a license file](https://github.com/alexhaydock/pinewall/blob/master/LICENSE), since I noticed I'd somehow managed to forget to do that so far. This repo is mostly basic config files so I'm not sure to what extent most of it is even original enough to fall under copyright law, but I picked a nice permissive license anyway so it's clear to people that they're free to use and build on what they find here.

**Comment by andybroger** [comment]
> Those performance stats are genuinely impressive! 😮 I didn't expect such high performance honestly. Are you using the default R8169 module to provide the drivers for the DFRobot NIC?

Just de default R8169 modules, no custom drivers for the nic needed.

> Also good to hear! I'd be particularly interested to see a decent netflow config using this setup! That's one that is definitely on my wishlist for the project in the futur

Netflow is pretty cool, but i don't know if its the right tool for a firewall. I want to have a modern logging, with application metadata, but i dont want to implement a IPS as i dont see any usecase for this in the future when 100% is encrypted traffic. And i dont want to intercept TLS. I have some ideas in mind, just need the time to test it.

> Feel free, I definitely encourage it - especially if you are making improvements to what I've got here! I added a license file, since I noticed I'd somehow managed to forget to do that so far. This repo is mostly basic config files so I'm not sure to what extent most of it is even original enough to fall under copyright law, but I picked a nice permissive license anyway so it's clear to people that they're free to use and build on what they find here.

Thanks for adding the License and allow me to use your base. I will do a PR in the future, as soon as the pinewall-rpi hits v1 and I battle-tested it at home.

**Comment by alexhaydock** [comment]
Closing this as I've now been running this on a Pi in production for a few months now and the Pi image is now the preferred one.
