### ISSUE TITLE
Nitpick: Prune old binary files from repo

### ISSUE THREAD

**Issue by vaskozl** [alexhaydock/pinewall#5]
At some point in time there was a PXE tftpboot directory with some big files:
 
https://github.com/alexhaydock/pinewall/commit/0e536ab865414f131470a4f5745d12aede779f70

Would make it nicer to fork for a personal config (as recommended) if those were removed as then `.git` wouldn't be 400Mi+.

**Comment by alexhaydock** [comment]
Good catch - I had a whole netboot config in here a while ago with a bunch of common initramfs files, but I eventually moved them elsewhere.

I'll see what I can do about squashing some of the Git history so it's not so large.

**Comment by alexhaydock** [comment]
I had a look at trying to interactively replay commits across the history and manually resolve the resultant merge conflicts, but it was ending up being quite a lot of work.

I know it's bad form to squash Git history so extremely, but since this isn't a collaborative project and it's only been my own commits so far, I figured there wasn't anything too useful in the Git history to preserve so far, so I've squashed most of it into a single large commit (5878cfad597cf8e0484b79b146bdb59323c6b8a3).

I'll avoid committing any binary files to the repo in the future.

On the plus side, we have gone from a 541M initial clone down to 532K, which is a nice 1000x saving.
